I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 67, in script call
    $ renpy.call(target_label)
  File "game/labels/location/mountain.rpy", line 39, in script call
    call lb_location_mountain_main_mine_gems()
  File "game/labels/location/mountain.rpy", line 57, in script
    python:
  File "game/labels/location/mountain.rpy", line 62, in <module>
    [gems_counts, names] = game.dragon.miner.getStringOfMinedGems(gems)
KeyError: 'genitive'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 67, in script call
    $ renpy.call(target_label)
  File "game/labels/location/mountain.rpy", line 39, in script call
    call lb_location_mountain_main_mine_gems()
  File "game/labels/location/mountain.rpy", line 57, in script
    python:
  File "/home/g2/Games/DefilerWings/DefilerWings-1.4.1-all-noteat2/renpy/ast.py", line 805, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/g2/Games/DefilerWings/DefilerWings-1.4.1-all-noteat2/renpy/python.py", line 1460, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/labels/location/mountain.rpy", line 62, in <module>
    [gems_counts, names] = game.dragon.miner.getStringOfMinedGems(gems)
  File "pythoncode/characters/dragon.py", line 118, in getStringOfMinedGems
KeyError: 'genitive'

Linux-5.15.0-71-generic-x86_64-with-debian-bookworm-sid
Ren'Py 6.99.7.858
Defiler Wings 1.4.1
